# Generated by Django 3.2 on 2021-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qodex_achive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, null=True)),
                ('restored', models.BooleanField(blank=True, null=True)),
                ('restored_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
