# Generated by Django 3.2 on 2021-04-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_qodex_achive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cm_events_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('event', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=12, null=True)),
                ('ex_id', models.IntegerField(blank=True, null=True)),
                ('upd_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cm_events_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Qodex_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('weight_fault', models.IntegerField(blank=True, null=True)),
                ('connected', models.BooleanField(blank=True, null=True)),
                ('inn', models.CharField(blank=True, max_length=20, null=True)),
                ('kpp', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Qodex_user',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='operators',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='qodex_achive',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='operators',
            table='Operators',
        ),
        migrations.AlterModelTable(
            name='qodex_achive',
            table='Qodex_achive',
        ),
    ]
