# Generated by Django 3.2 on 2021-04-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210424_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='cm_events_log',
            name='poligon',
            field=models.ForeignKey(blank=True, db_column='poligon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users'),
        ),
        migrations.AddField(
            model_name='operators',
            name='poligon',
            field=models.ForeignKey(blank=True, db_column='poligon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users'),
        ),
        migrations.AddField(
            model_name='qodex_achive',
            name='poligon',
            field=models.ForeignKey(blank=True, db_column='poligon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.qodex_users'),
        ),
    ]
